name: Actions test
on: [push]
jobs:
  Github-Actions-MVN-Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Prepare passsword DB
        env: # Or as an environment variable
          SQL_DRIVER: ${{ secrets.SQL_DRIVER }} 
          SQL_PASSWORD: root
          SQL_USER: root
          SQL_URL: jdbc:h2:~/amt_pianorgue
        run: ./script/prepare-db.sh
      - name: Setup mysql for runtime testdb
        run: |
                sudo /etc/init.d/mysql start
                echo 'CREATE DATABASE pianorgue;' > mysql -u${{ env.SQL_USER }} -p${{ env.SQL_PASSWORD }}
      - name: MVN Verify
        working-directory: ./application/
        run: mvn --batch-mode --update-snapshots verify
